version: "3.3"

services:
  secret-simulator:
    image: mikesir87/secrets-simulator
    volumes:
      - secrets:/run/secrets:rw
    environment:
      JWT_SECRET: 7xscu8H1NbJ5IRWZ24k3OYjdQ2udm0wIt0xEF83iAV7jaRJsHYfgSu9uANLUy7HW
      DB_HOST: 192.168.3.190
      DB_NAME: ng5tohazsecuredemo
      DB_USER_NAME: commonuser
      DB_PASSWORD: xyz123irqc3657*
  ng_toh_az_ssi_secret_simulator:
    image: iameprel/ng_toh_az_ssi_secret_simulator:1.1
    user: root
    working_dir: /usr/src/app
    volumes:
      - secrets:/run/secrets:ro
    build: .
    ports:
      - 4000:3000

volumes:
  secrets:
    driver: local
