version: '2.0'

services:
  ng_toh_az_ssi:
    image: iameprel/ng_toh_az_ssi:1.1
    user: root
    working_dir: /usr/src/app
    build: .
    env_file: env_file
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000