version: "3.3"
services:
  secret-simulator:
    image: mikesir87/secrets-simulator
    volumes:
      - secrets:/run/secrets:rw
    environment:
      JWT_SECRET: your-jwt-secret
      DB_MODE: your-db-mode
      DB_HOST: your-host-ip
      DB_NAME: your-database-name
      DB_USER_NAME: your-mongo-root-user
      DB_PASSWORD: your-mongo-root-password
  web:
    image: iameprel/angular
    deploy:
      replicas: 10
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    user: root
    working_dir: /usr/src/app
    # when using just a mounted secret folder
    # volumes:
    #   - ./secrets:/run/secrets
    # I prefer something more freakin easy not to mention awesome
    volumes:
      - secrets:/run/secrets:ro
    # build is ignored on stack deploy to swarm
    # build: .
    environment:
      NODE_ENV: development
    ports:
      - 4000:3000
    # links are ignored on stack deploy to swarm
    # links:
    #   - mongoDb:mongoDb
    depends_on:
      - mongoDb
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  # Please REMOVE all the mongoDB service section when deploying in PRODUCTION
  mongoDb:
    image: mongo:3.7
    environment:
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=mongo-root-user
      - MONGO_INITDB_ROOT_PASSWORD=mongo-root-password
    volumes:
      - /data/db:/data/db:rw
      # if you wish to setup additional user accounts specific per DB or with different roles you can use following entry point
      # just create docker-entrypoint.sh file and follow the instructions online
      # - ./mongo-entrypoint/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
    # This does not enforce authentication.
    # command: mongod
    # This here enforces the need for authentication.
    command: mongod --auth --smallfiles --port 27017 --dbpath /data/db --logpath=/dev/null --quiet
volumes:
  secrets:
    driver: local
networks:
  webnet:
    # driver: overlay