version: "3.3"

services:
  ng_toh_az_ssi_secret_swarm:
    image: iameprel/ng_toh_az_ssi_secret_swarm:1.1
    user: root
    working_dir: /usr/src/app
    secrets:
      - DB_HOST
      - DB_NAME
      - DB_USER_NAME
      - DB_PASSWORD
      - JWT_SECRET
    build: .
    ports:
      - 4000:3000
secrets:
  DB_HOST:
    external: true
  DB_NAME:
    external: true
  DB_USER_NAME:
    external: true
  DB_PASSWORD:
    external: true
  JWT_SECRET:
    external: true
