version: "3.3"

services:
  ngtohssimongo:
    image: iameprel/ngtohssimongo:1.0.0
    user: root
    working_dir: /usr/src/app
    volumes:
      - ./secrets:/run/secrets
    build: .
    ports:
      - 4000:3000

